### ISSUE TITLE
Update implementation of Redux Toolkit

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#103]
**Describe the bug**
The current implementation of Redux Toolkit is outdated. In the terminal, this is the warning received:
`/!\ You are using legacy implementation. Please update your code: use createWrapper() and wrapper.useWrappedStore().`

**To Reproduce**

1. Open the project's directory in your terminal
2. Run yarn dev
3. See warning in terminal

**Expected behavior**
An up-to-date implementation of Redux toolkit should remove this warning

**Screenshots**
![image](https://github.com/quizardhq/frontend/assets/49480381/051e0232-8881-4724-9d2e-cd00140cf4eb)

**Desktop (please complete the following information):**

- OS: [Windows 10 Pro]

**Comment by Mide001** [comment]
can you assign this to me?
