### ISSUE TITLE
Add scroll transitions

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#107]
**Is your feature request related to a problem? Please describe.**
Currently, the FAQs don't open smoothly, and the links in the header don't smoothly scroll to their linked sections.

**Describe the solution you'd like**
I want the FAQs to smoothly open up when clicked, and the links in the header to scroll smoothly to the appropriate sections

**Comment by amrinder1189** [comment]
Hi please assign this task to me

**Comment by CeoFred** [comment]
Go ahead @amrinder1189
