### ISSUE TITLE
Wrong border color for github icon

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#111]
**Describe the bug**
The border color for github icon on desktop and mobile is grey.

**To Reproduce**

1. Go to Homepage
2. Look at the nav bar and locate the github icon if you are on desktop, on mobile, open
the navigation bar and see the github icon border.

**Expected behavior**
The border color should be the primary color

**Screenshots**
<img width="531" alt="Screen Shot 2023-05-13 at 07 06 11" src="https://github.com/quizardhq/frontend/assets/32965534/4ec8cef3-c12a-4619-a668-72b6a1d8a1b5">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amrinder1189** [comment]
Hi @CeoFred , can you please tell what color i need to apply to the border ? . Thanks

**Comment by CeoFred** [comment]
the color is 'primary'
