### ISSUE TITLE
Add Firstname and lastname field to waitlist form

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#122]
**Is your feature request related to a problem? Please describe.**
The current waitlist form on our website only collects a single field for user input, such as an email address. However, in order to personalize our communication with waitlist subscribers, it would be beneficial to collect both the first name and last name of users. This additional information will enable us to address subscribers by their names and provide a more personalized experience.

**Describe the solution you'd like**
I would like to request that we add separate fields for collecting the first name and last name of users to our waitlist form. This will allow users to enter their complete name when subscribing to the waitlist. By capturing this information, we can personalize our communication and make the waitlist experience more personable and engaging for users.

**Describe alternatives you've considered**
One alternative solution would be to continue using the current waitlist form with only the email field, and manually collect the first name and last name information later through a separate process. However, this can be inconvenient for users and may lead to a lower conversion rate. Another alternative solution would be to use a social media login option to automatically retrieve the user's name. However, not all users may have social media accounts or may not want to provide access to their social media profiles.

**Additional context**
Collecting the first name and last name of users on our waitlist form will allow us to establish a more personalized connection with subscribers. By addressing users by their names in our communication, we can create a sense of familiarity and enhance the overall user experience. Adding these fields to the waitlist form will also streamline our data collection process and enable more targeted and effective communication with our waitlist subscribers.

**Comment by CeoFred** [comment]
Figma design https://www.figma.com/file/II0muRKX2Emc6M0ocw7u9Y/Quizard?type=design&node-id=1433-21473&t=rM5KYSASrYKIOyq2-4

**Comment by keven321** [comment]
Can I work on this? For my skills, I would be able to just add the input fields but I won't be able to handle any of the logic of form is that ok?

**Comment by CeoFred** [comment]
Yeas go ahead @keven321

**Comment by keven321** [comment]
Is this design ok I couldn't figure out how to do it like in the Figma design but if it's not I'll keep working on it. 
![image](https://github.com/quizardhq/frontend/assets/63021403/8731112d-1806-426f-a104-25f6b9afc179)

**Comment by dpkreativ** [comment]
> Is this design ok I couldn't figure out how to do it like in the Figma design but if it's not I'll keep working on it. ![image](https://user-images.githubusercontent.com/63021403/238455812-8731112d-1806-426f-a104-25f6b9afc179.png)

yeah keep working on it... what are you using for the CSS? We could hop on a call tomorrow and collaborate on it

**Comment by keven321** [comment]
Yeah we can work on it together. What do you use for communication?

**Comment by keven321** [comment]
I was able to fix the problem I was having with the design would you like me to make a PR with the changes?

**Comment by CeoFred** [comment]
Yea, go ahead and let me see what you've got. @keven321

**Comment by keven321** [comment]
I created the PR for the input fields I added. They don't have any functionality though.
