### ISSUE TITLE
Implement Signup page Design

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#140]
**Is your feature request related to a problem? Please describe.**
Currently, our application does not have a dedicated signup page, which can make it confusing for new users who want to create an account. Implementing a new signup page design is essential to provide a clear and intuitive user experience, enabling users to easily sign up and access the features of our application.

**Describe the solution you'd like**
I would like to implement a new signup page design that offers a user-friendly interface for creating an account. The design should incorporate essential elements such as input fields for personal information (e.g., name, email, password), a visually appealing layout, and clear instructions or tooltips to guide users through the signup process. It should also include relevant validation checks to ensure the accuracy and completeness of user-provided data.

**Describe alternatives you've considered**
One alternative approach would be to use a modal or popup for the signup process instead of a dedicated signup page. However, implementing a standalone signup page provides more flexibility for customization and future enhancements, such as adding additional steps or integrating third-party signup options.

**Additional context**
By implementing a new signup page design, we can streamline the user onboarding process and provide a seamless experience for new users. The design should align with our application's overall look and feel, reinforcing our branding and visual identity. A well-designed and intuitive signup page encourages more users to create accounts, fosters a positive first impression, and increases the likelihood of user engagement with our application. Additionally, having a dedicated signup page opens up possibilities for implementing additional features in the future, such as social media signups or capturing optional user preferences during the registration process.

**Comment by dpkreativ** [comment]
@CeoFred I'm currently working on this
