### ISSUE TITLE
Add Netlify badge to README.md

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#28]
This badge will enable us track the status of our Netlify builds

**Comment by dpkreativ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Netlify Badge to README.md](https://trello.com/c/uL7Vf212/2-add-netlify-badge-to-readmemd)

**Comment by Mide001** [comment]
@dpkreativ i would like to work on this.

**Comment by dpkreativ** [comment]
Awesome! let's get started
