### ISSUE TITLE
Animate coming soon page

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#30]
Add fun scrolling animations to the page
Get creative with it

**Comment by dpkreativ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Animate Coming Soon page](https://trello.com/c/vC790Xib/6-animate-coming-soon-page)

**Comment by AdrianaMoralesQ** [comment]
Hi, I'd like to give this a go! I've sent you a Trello Request :)

**Comment by dpkreativ** [comment]
I've added you to the Trello board 👍

**Comment by dpkreativ** [comment]
@AdrianaMoralesQ thanks for the #59 PR, would you be working on some extra animations?
