### ISSUE TITLE
Update README.md with better, more concise content

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#35]
## The challenge
At the moment, the README.md file looks okay, but it could look much better to read.

## Definition of "Done"
- The README.md looks much better than it currently is, and properly explains the project
- There are helpful links for contributing to the codebase

**Comment by dpkreativ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update README.md with better, more concise content](https://trello.com/c/pwXO6mEP/13-update-readmemd-with-better-more-concise-content)

**Comment by dpkreativ** [comment]
Keep this in mind:
_Click on it for more info_
<a href="https://opensource.guide/starting-a-project/#writing-a-readme">
![image](https://user-images.githubusercontent.com/49480381/226164576-61666633-8fe9-4f81-a310-d616ee3c88fc.png)
</a>

**Comment by dpkreativ** [comment]
@Mide001 would you still be working on this?

**Comment by dpkreativ** [comment]
@tanvirraihanislam you're taking this up right?

**Comment by tanvirraihanislam** [comment]
> @tanvirraihanislam you're taking this up right?

Yes @dpkreativ

**Comment by dpkreativ** [comment]
Done @tanvirraihanislam

**Comment by dpkreativ** [comment]
https://opensource.guide/starting-a-project/#writing-a-readme

**Comment by dpkreativ** [comment]
Thanks for working on this issue @tanvirraihanislam 

We're closing it now as it is complete
