### ISSUE TITLE
Setup Docker for development

### ISSUE THREAD

**Issue by davydocsurg** [quizardhq/frontend#38]
Here are some benefits of Dockerizing this frontend repo:

- Consistent Development Environment: Docker will help create a consistent development environment for all contributors working on this repo, regardless of their operating system or environment. This ensures that everyone is working with the same dependencies and configuration, which reduces the likelihood of errors or bugs due to differences in environments.
- Isolation: Docker containers provide isolation from the host system and other containers, which helps to prevent conflicts with other applications and services running on the same machine.
- Scalability: Docker will make it easy to scale this repo horizontally by spinning up additional containers to handle increased traffic or workload.
- Faster Build and Deployment: Docker allows for faster build and deployment times by using cached layers and reducing the time required to spin up a new container.

**Comment by CeoFred** [comment]
We are deploying to netlify, how do you tackle this? @davydocsurg or does not affect?

**Comment by davydocsurg** [comment]
The primary aim of setting up Docker is to make development seamless for all contributors regardless of their operating systems or development environments and also aid deployment.

**Comment by CeoFred** [comment]
I'll assign this to you @davydocsurg

**Comment by davydocsurg** [comment]
Alright, @CeoFred 
On it

**Comment by dpkreativ** [comment]
Thanks for working on this @davydocsurg
