### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#44]
We're migrating the codebase to TypeScript now that it's still in its early stages, cos migrating at a later stage could be more time-consuming

**Comment by dpkreativ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate to TypeScript](https://trello.com/c/qF4sUTov/20-migrate-to-typescript)

**Comment by CeoFred** [comment]
https://github.com/quizardhq/frontend/pull/64
