### ISSUE TITLE
Fix broken navbar link on the Quizard home page

### ISSUE THREAD

**Issue by whalewalker** [quizardhq/frontend#48]
When I go to https://quizardhq.com/
The navbar links are not clickable

**Comment by CeoFred** [comment]
The links are meant to point to different sections of the page, using id attributes and smooth scrolling should fix this..

**Comment by sra1kumar-NULL** [comment]
hey @CeoFred  can I work on this is this still open ?

**Comment by dpkreativ** [comment]
This is has been resolved. Thanks @whalewalker
