### ISSUE TITLE
Improve email address validation on the landing page

### ISSUE THREAD

**Issue by whalewalker** [quizardhq/frontend#49]
I was able to submit an incorrect email address (ohida22@GM) on the landing page https://quizardhq.com/"

**Comment by tanvirraihanislam** [comment]
Hi @dpkreativ , can you please assign this task to me?
I can start working on this from tomorrow. 
Thank you

**Comment by dpkreativ** [comment]
@tanvirraihanislam please go ahead. Thanks

**Comment by dpkreativ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve email address validation on the landing page](https://trello.com/c/yeWqAw0G/17-improve-email-address-validation-on-the-landing-page)
