### ISSUE TITLE
Fix issue with burger icon not displaying navbar when clicked on Quizard landing page for small screens

### ISSUE THREAD

**Issue by whalewalker** [quizardhq/frontend#50]
When viewed on a smaller screen, clicking the burger icon does not display the dropdown menu for the navbar links on the page

**Comment by CeoFred** [comment]
the feature is yet to be implemented by the core-team, thanks for raising this issue.

**Comment by dpkreativ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix issue with burger icon not displaying navbar when clicked on Quizard landing page for small screens](https://trello.com/c/4SF2gchW/19-fix-issue-with-burger-icon-not-displaying-navbar-when-clicked-on-quizard-landing-page-for-small-screens)

**Comment by HelenJonathan** [comment]
Hi @dpkreativ can i work on this?

**Comment by dpkreativ** [comment]
Okay @HelenJonathan I'm assigning it to you now
