### ISSUE TITLE
Fix background color issue when using autocompletion to fill out the waitlist form on the landing page

### ISSUE THREAD

**Issue by whalewalker** [quizardhq/frontend#51]
<img width="527" alt="Screenshot 2023-03-25 at 5 51 50 AM" src="https://user-images.githubusercontent.com/80593013/227697103-44ae0c3b-735c-4322-b7af-f30f3d5dcabd.png">

**Comment by CeoFred** [comment]
@whalewalker  thanks for spotting that, you have been assigned

**Comment by whalewalker** [comment]
@CeoFred, there are two possible solutions to address the issue mentioned above:

1. Disable the autocomplete feature for the form.
2. Develop a CSS file and apply browser-specific styling to it.

**Comment by dpkreativ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix background color issue when using autocompletion to fill out the waitlist form on the landing page](https://trello.com/c/7wz7ltwz/16-fix-background-color-issue-when-using-autocompletion-to-fill-out-the-waitlist-form-on-the-landing-page)
