### ISSUE TITLE
Set up Husky in Quizard's frontend Docker image

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#60]
**Is your feature request related to a problem? Please describe.**
The problem is that we do not have a linter in Quizard's frontend Docker image. We have set up Husky on the main codebase, but for contributors who want to use Docker, there's no way to lint their code.

**Describe the solution you'd like**
I would like to request the addition of Husky, a Git hook tool, to be included in Quizard's frontend Docker image. Husky will allow us to run linting and formatting checks before committing our code, ensuring that the codebase is consistent and meets our coding standards. This will make it easier to maintain the codebase and reduce the likelihood of introducing bugs or errors into the code.

**Describe alternatives you've considered**
One alternative we have considered is setting up Husky on each developer's local machine. This works, but I noticed that the configuration is inconsistent across different operating systems. By including Husky in the Docker image, we can ensure that every developer uses the same configuration, reducing the likelihood of inconsistencies in the codebase.

**Additional context**
Husky is a popular Git hook tool that is easy to use and widely adopted in the development community. Its large community of users and contributors makes it a reliable and well-supported tool for maintaining code quality.

**Comment by tanvirraihanislam** [comment]
Hi @dpkreativ, I can start working on this from Monday. If that's okay with you, can you please assign me this?

**Comment by CeoFred** [comment]
Done
