### ISSUE TITLE
Create a custom 404 page

### ISSUE THREAD

**Issue by dpkreativ** [quizardhq/frontend#61]
**Is your feature request related to a problem? Please describe.**
When users encounter a broken link or mistyped URL on the Quizard website, they are redirected to a generic 404 error page. This can be confusing and frustrating for users who may have been looking for specific information on the site.

**Describe the solution you'd like**
I would like to request the implementation of a custom 404 error page for the Quizard website. This page should clearly communicate to users that the page they were looking for cannot be found and provide helpful suggestions for navigating the site and finding the information they need. The page should also include branding elements and design consistent with the rest of the site.

**Describe alternatives you've considered**
One alternative solution could be to leave the generic 404 error page in place. However, this would not give users the helpful guidance and direction a custom page could offer.

**Additional context**
A custom 404 error page would not only improve the user experience on the Quizard website, but it could also help to reduce the bounce rate and improve overall site engagement.

**Comment by dpkreativ** [comment]
The design team might need to work on this first

**Comment by CeoFred** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a 404 error page](https://trello.com/c/dn7JnTkW/23-create-a-404-error-page)
