### ISSUE TITLE
Global State Management

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#70]
**Is your feature request related to a problem? Please describe.**
Currently, our application lacks a centralized approach to managing the state of the application. This can lead to inconsistency and complexity in our codebase, making it harder to maintain and extend the application. A global state management system would simplify our code and improve the scalability of our application.

**Describe the solution you'd like**
I would like to request that we implement a global state management system in our application. There are several popular state management libraries available such as Redux and MobX, which can provide us with the necessary tools for implementing a centralized approach to managing the state of our application. The implementation of a global state management system will help us to manage the state of our application in a more organized and efficient manner.

**Describe alternatives you've considered**
One alternative solution would be to continue managing the state of our application using local state and passing props between components. However, this approach can lead to inconsistency and complexity in our codebase, making it harder to maintain and extend the application. Another alternative solution would be to use context API, but it may not be suitable for larger and more complex applications.

**Additional context**
Global state management is a widely adopted practice in modern web development, and implementing it in our application will help us to simplify our code and improve the scalability of our application. It will also make our code more organized and efficient, leading to better maintainability and extensibility of the application.

**Comment by CeoFred** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Github icon to navigation bar](https://trello.com/c/15W6GETZ/22-add-github-icon-to-navigation-bar)

**Comment by CeoFred** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate Redux tool kit](https://trello.com/c/HNYWBgTh/24-integrate-redux-tool-kit)

**Comment by dpkreativ** [comment]
@CeoFred will you consider this issue fixed?

**Comment by CeoFred** [comment]
yeas, i added extra functionality...although there seems to be a warning on
the terminal, i don't know if we should be worried.
