### ISSUE TITLE
Add Github Icon to Navigation Bar

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#71]
**Is your feature request related to a problem? Please describe.**
Currently, our website's navigation bar does not include an icon for linking to our Github repository. This can make it difficult for users to find and access our Github page, which contains important project information and source code. Adding a Github icon to the navigation bar would improve user experience and make it easier for users to navigate to our Github repository.

**Describe the solution you'd like**
I would like to request that we add a Github icon to our website's navigation bar. The icon should be clickable and link to our Github repository. Ideally, the icon should be placed in a prominent location in the navigation bar so that users can easily locate it.

**Describe alternatives you've considered**
One alternative solution would be to include a text link to our Github repository in the navigation bar instead of an icon. However, this would not be as visually appealing as an icon and may be less noticeable to users.

**Additional context**
Our Github repository contains important project information and source code, and we would like to make it as easy as possible for users to access this information. Adding a Github icon to the navigation bar is a simple and effective way to improve the user experience and increase visibility of our repository.

**Comment by CeoFred** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Github icon to navigation bar](https://trello.com/c/15W6GETZ/22-add-github-icon-to-navigation-bar)

**Comment by keven321** [comment]
Hello, can I work on this issue?

**Comment by CeoFred** [comment]
Yeas you can... reference the figma design @keven321  https://www.figma.com/file/II0muRKX2Emc6M0ocw7u9Y/Quizard?node-id=14%3A799&t=LfiwjQyPV7mARsYF-1

**Comment by keven321** [comment]
I was able to add the GitHub icon to the navigation bar but I'm having trouble trying to commit the changes I made I'm getting this error message and I don't know what it means and how to fix it. Sorry, I'm new to this and this is my first time contributing to an open-source project. Here is a screenshot of what I'm getting: 
![image](https://user-images.githubusercontent.com/63021403/236643649-c3e3afcb-3138-4ec3-9c97-eed71eea560d.png)

**Comment by CeoFred** [comment]
run yarn format .

**Comment by keven321** [comment]
Thank you it works I made the pull request.
