### ISSUE TITLE
Footer Section 

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#72]
**Is your feature request related to a problem? Please describe.**
Our website is missing a footer section, which is an important component of any website. A footer section typically contains important information such as contact details, links to social media, copyright information, and other important details. The lack of a footer section can make our website look incomplete and unprofessional.

**Describe the solution you'd like**
I would like to request that we add a footer section to our website. The footer section should be designed in a way that is consistent with the overall look and feel of the website. It should contain important information such as contact details, links to social media, copyright information, and other relevant details.

**Describe alternatives you've considered**
One alternative solution would be to add the information that would normally be included in the footer section to other parts of the website, such as the header or body. However, this can make the website look cluttered and disorganized, and can also make it harder for users to find the information they are looking for.

**Additional context**
A footer section is an essential component of any website, and it is important that we add one to our website as soon as possible. The footer section will provide users with important information about our website and organization, and will make our website look more professional and complete.

**Comment by tayyab-ilyas** [comment]
I'd like to work on this @CeoFred

**Comment by CeoFred** [comment]
You'll need to work with the design for this. https://www.figma.com/file/II0muRKX2Emc6M0ocw7u9Y/Quizard?node-id=14%3A799&t=LfiwjQyPV7mARsYF-1
