### ISSUE TITLE
Meet the Team Section should be a carousel slide

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#81]
**Is your feature request related to a problem? Please describe.**
Our website's Meet the Team section is currently static and lacks interactivity, which can make it less engaging for users. A static Meet the Team section also limits the amount of information we can provide about our team members, and may not be an effective way to showcase the diversity and expertise of our team.

**Describe the solution you'd like**
I would like to request that we change the Meet the Team section of our website to a carousel slide. A carousel slide would allow us to include more team members and provide additional information about each team member, such as their role, expertise, and background. A carousel slide would also make the Meet the Team section more engaging and interactive, improving the overall user experience.

**Describe alternatives you've considered**
One alternative solution would be to create a separate page for the Meet the Team section, with individual profiles for each team member. However, this approach may not be as visually appealing or as user-friendly as a carousel slide. Another alternative solution would be to keep the Meet the Team section static but add more information about each team member. However, this may make the section too long and difficult to read.

**Additional context**
A carousel slide is a popular and effective way to showcase team members on a website. It allows for more information to be displayed in a visually appealing and interactive way, which can help to engage users and showcase the diversity and expertise of our team. Changing the Meet the Team section to a carousel slide will also make our website look more modern and up-to-date.

**Comment by dpkreativ** [comment]
Working on this @CeoFred

**Comment by CeoFred** [comment]
@all-contributors please add @dpkreativ  for code
