### ISSUE TITLE
Bug: NavItems and Hamburger MenuIcon behavior

### ISSUE THREAD

**Issue by brightiortsor** [quizardhq/frontend#90]
**The bug**

- `Github Link Container`: When you visit the website and try to click on any other space within the container, it is expected that it the link is visited. However, this isnt the case even though the container has a `cursor: pointer` but only the icon is clickable and not the whole container (even though it has a pointer). This behaviour is most visible on md and sm screens where the Hamburger menu is visible as the width of the `Github Link Container` is now increased thus creating more padding.

- `Hamburger MenuIcon`: This is supposed to be clickable and as such should have a `cursor: pointer;` effect but that isnt the case currently.
-  `Nav Items`: Currently, you can't tell when hovering on the NavItems. Ideally, it is expected that the NavItems should have a hover effect(s) to help the user know when they are navigating those items.

**Comment by brightiortsor** [comment]
I can't currently clone the project. Something about ` invalid path 'public/assets/og:image.png'`
Please advise.
Thank you.

![quizard](https://user-images.githubusercontent.com/99312664/236773650-9e3ac54d-0013-44b7-88c3-6049aea04d51.png)

**Comment by CeoFred** [comment]
I'm not we have such path, try cloning the staging branch or re-clone.

**Comment by CeoFred** [comment]
join the slack workspace https://join.slack.com/t/quizardhq/shared_invite/zt-1uys4uo7k-PNdgNv0bdsk7Ezb52HMhfg

**Comment by brightiortsor** [comment]
The path error is as a result of the og:image.png added according to the error displayed from the terminal. I have recloned 3x now. Both main and staging but same path error.

**Comment by dpkreativ** [comment]
@brightiortsor what's the update on this?

**Comment by dpkreativ** [comment]
Let's hop on a Google Meet and sort this out. Check your DM on Slack
