### ISSUE TITLE
Input Placeholder text at footer is a headache

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#96]
**Describe the bug**
The text placeholder color of the input at the footer is gray in color 

**To Reproduce**

1. Go to the home page
2. Scroll down to the bottom
3. You'll notice the placeholder text is gray or so

**Expected behavior**
The color of that placeholder should be white

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.6.3 
- Browser: chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dpkreativ** [comment]
@Mide001 would you be working on this?

**Comment by Mide001** [comment]
Yeah

**Comment by dpkreativ** [comment]
@Mide001 I've assigned it to you. Pls remember to pull the latest changes first, and work on this issue in a separate branch. Thank you
