### ISSUE TITLE
Fix Social and internal page links

### ISSUE THREAD

**Issue by CeoFred** [quizardhq/frontend#97]
**Describe the bug**
All links on the footer of the website goes to the wrong place. 

**To Reproduce**

1. Go to Home page
2. Scroll down to the footer
3. Attempt clicking the links

**Expected behavior**
Links should navigate to the appropriate destination

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mide001** [comment]
Can you assign this to me?

**Comment by dpkreativ** [comment]
@Mide001 work on this one 👍🏾

**Comment by dpkreativ** [comment]
okay
