### ISSUE TITLE
Bug: Work on the Sections Transition using the Navbar 

### ISSUE THREAD

**Issue by gateremark** [quizardhq/frontend#99]
**Describe the bug**
The navbar does not work in transitioning in both the 'About Us' and 'FAQ' Section.

**To Reproduce**

1. Open the page
2. Using the Navbar, click 'Features'
3. Using the Navbar, click 'About Us' or 'FAQ'
4. The page does not head to the 'About Us' or 'FAQ' section with the Navbar

**Expected behavior**
Expected to work in a similar manner as after clicking the 'Features' Section.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge
- Version: Latest Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CeoFred** [comment]
@gateremark i've assigned this to you.

**Comment by gateremark** [comment]
On it sir.

**Comment by gateremark** [comment]
Done, and have already created a PR.

**Comment by dpkreativ** [comment]
@gateremark still working on this?

**Comment by gateremark** [comment]
@dpkreativ I worked on it, created a PR but @CeoFred made similar changes on the main quizardhq staging branch which led to conflict hence I Synced my fork to the commits made to prevent the conflict. Seems @CeoFred worked on it.
